### PR TITLE
Feature/contributions page

### PR DESCRIPTION
**Pull request by dnietoBlackBoard**
This commit adds the index page for the community contributions in the organization https://github.com/anthology-developer-hub.

### CODE REVIEW

**Comment by mark-b-kauffman** [comment]
Is there a link to get to the contributions index from the left side bar navigation or another place? Or do you have to know the URL?

**Comment by dnietoBlackBoard** [comment]
Hi Mark, the link for accessing it could be found in the navigation at the top page next to the Blogs link.

image

**Review by mark-b-kauffman — APPROVED** [review]
Looks good!

**Comment by OneComputerGuy** [comment]
LGTM

**Pull request merged**
